services:
  - type: web
    name: my-node-app
    env: node
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    branch: main
    runtime:
      node: 20
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_GOOGLE_CLIENT_ID
        value: your-google-client-id
